version: "3.8"

volumes:
  prometheus_data: {}

services:
  prometheus:
    image: prom/prometheus:v2.20.1
    volumes:
      - ./prometheus:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    ports:
      - 9090:9090

  metricssimulator:
    build: ./
    ports:
    - 8080:8080